INSERT INTO `question` (`question_id`,`que_id`, `que`) VALUES
 (1,  'Q.1','Is your child speaking?'),
 (2,  'Q.2','Has your child been diagnosed with autism'),
 (3,  'Q.3','Is your child undergoing speech therapy?'),
 (4,  'Q.4','Do you see any improvements in your child s speech with speech therapy?'),
 (5,  'Q.5','For how long has your child been undergoing speech therapy?'),
 (6,  'Q.6','Why is he/she not undergoing speech therapy?'),
 (7,  'Q.7','Do you expect your child will speak ?'),
 (8,  'Q.8','Why do you think so?'),
 (9,  'Q.9','why do you think so?'),
 (10, 'Q.10','Did any doctor or any other professional tell you your child will not speak?'),
 (11, 'Q.11','What was the qualification of the professional who told you so?'),
 (12, 'Q.12','Do you believe what the professionals say about your child s ability to speak or not speak?'),
 (13, 'Q.13','What makes you believe what they tell you?'),
 (14, 'Q.14','What makes you not believe what they tell you?'),
 (15, 'Q.15','Do you think your expectations from your child can help or prevent him/her from being able to speak?'),
 (16, 'Q.16','Do you think the expectations from the care-givers interacting with your child can help or prevent him/her from speaking?'),
 (17, 'Q.17','Does your child get seizures?'),
 (18, 'Q.18','Then how often does your child get the seizures?'),
 (19, 'Q.19','Is your child on medication for seizures? If yes, what medications and since how long?'),
 (20, 'Q.20','How effective were the medicines in controlling the symptoms of autism and/or ADHD in your child ?'),
 (21, 'Q.21','Do you think the symptoms of autism in your child are due to the seizures?'),
 (22, 'Q.22','Why do you think so?'),
 (23, 'Q.23','Then what do you think is causing the symptoms of autism in your child?'),
 (24, 'Q.24','Do you think the Seizures in your child is due to the autism?'),
 (25, 'Q.25','Why do you think so?'),
 (26, 'Q.26','What do you think is causing the seizures?'),
 (27, 'Q.27','Do you think your child can be completely cured of the seizures?'),
 (28, 'Q.28','How do you think that is possible?'),
 (29, 'Q.29','Why do you think it is not possible?'),
 (30, 'Q.30','Does your child suffer from gut issues?'),
 (31, 'Q.31','What are the issues relating to the gut he/she is facing?'),
 (32, 'Q.32','What were the gut issues your child had suffered from and how did they disappear?'),
 (33, 'Q.33','Have you given any medicines to your child to help treat the gut issues?'),
 (34, 'Q.34','What medicines have you given your child so far to help treat the gut issues?'),
 (35, 'Q.35','How effective were the medicines in helping cure the gut issues in your child?'),
 (36, 'Q.36','Why have you not tried/given any medicines for the gut issues?'),
 (37, 'Q.37','Do you think the gut issues in your child is due to autism?'),
 (38, 'Q.38','Why do you think so?'),
 (39, 'Q.39','What do you think is the cause for the gut issues in your child?'),
 (40, 'Q.40','Do you think the symptoms of autism in your child is due to the gut issues in your child?'),
 (41, 'Q.41','Why do you think so?'),
 (42, 'Q.42','Do you think your child can be completely cured of the gut issues?'),
 (43, 'Q.43','How do you think that is possible?'),
 (44, 'Q.44','Why do you think it is not possible?'),
 (45, 'Q.45','Has your child been diagnosed with Aspergers or high-functioning Autism?'),
 (46, 'Q.46','Who made the diagnosis?'),
 (47, 'Q.47','why do you think/feel your child has Aspergers/High-functiong autism?'),
 (48, 'Q.48','What are they?'),
 (49, 'Q.49','Do you think your child needs to be cured/healed of Asperger s /high-functioning autism?'),
 (50, 'Q.50','Why do you think so?'),
 (51, 'Q.51','Why do you think so?'),
 (52, 'Q.52','What are those issues that need to be cured/healed? List the same.'),
 (53, 'Q.53','Do you think your child having Asperger s / high-functioning autism is a gift or a blessing?'),
 (54, 'Q.54','Why do you think so?'),
 (55, 'Q.55','Why do you think so?'),
 (56, 'Q.56','Do you think Asperger s/high-functioning autism is the next stage in human evolution?'),
 (57, 'Q.57','Why do you think so?'),
 (58, 'Q.58','Why do you think so'),
 (59, 'Q.59','Has your child been diagnosed with developmental delay and/or PDD-NOS?'),
 (60, 'Q.60','Who made the diagnosis?'),
 (61, 'Q.61','What are the symptoms of developmental delay and/or PDD-NOS does your child have? List the same'),
 (62, 'Q.62','What do you think is the cause for the symptoms in your child?'),
 (63, 'Q.63','Do you think your child can be completely cured of the developmental delay and/or PDD-NOS?'),
 (64, 'Q.64','How do you think that is possible?'),
 (65, 'Q.65','Why do you think it is not possible?'),
 (66, 'Q.66','Has your child been diagnosed with ADHD along with Autism?'),
 (67, 'Q.67','Who made the diagnosis?'),
 (68, 'Q.68','Why do you think your child has ADHD with Autism?'),
 (69, 'Q.69','Which was diagnosed in your child first?'),
 (70, 'Q.70','What are the symptoms of ADHD does your child have? List the same.'),
 (71, 'Q.71','What do you think is the cause for the symptoms of ADHD in your child?'),
 (72, 'Q.72','Do you think your child can be completely cured of Autism and ADHD?'),
 (73, 'Q.73','How do you think that is possible?'),
 (74, 'Q.74','Why do you think it is not possible?'),
 (75, 'Q.75','Do you think your child can be completely cured of autism and any other associated conditions such as seizures, ADHD, Developmental Delay,  Gut Issues,  Sensory Processing Disorder and any other symptoms?"'),
 (76, 'Q.76','How do you think that is possible?'),
 (77, 'Q.77','Why do you think it is not possible?'),
 (78, 'Q.78','What are the symptoms of developmental delay and/or PDD-NOS does your child have? List the same.'),
 (79, 'Q.79','Does your child have any special interests or special talents?'),
 (80, 'Q.80','Have the symptoms of autism and/or adhd in your child worsened or improved with seizure medications?');

 
 
 
 